<?php
$conf=array(
    'table'=>array(
        'tbl_store',
        'tbl_store_activity',
        'tbl_store_comment',
        'tbl_store_memo',
        'tbl_store_menu',
        'tbl_store_position',
        'tbl_store_static',
        'tbl_store_type',
        'tbl_store_visit',
        'tbl_store_visit_static'
    ),
    'procedure'=>array(),
    'view'=>array()
);
?>